name: BTB22_CC_LAB
services:
  postgres:
    container_name: postgres-cc-lab
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    image: postgres

  pgadmin4:
    container_name: pgadmin4-cc-lab
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    depends_on:
      - postgres
  
  httpd:
    container_name: httpd-cc-lab
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    image: httpd

  node:
    image: node:22-alpine
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres